# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clonr < Formula
  desc "A fast and easy to use templating engine."
  homepage ""
  version "1.0.4"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.0.4/clonr_1.0.4_Darwin_x86_64.tar.gz"
      sha256 "97fbf22c3b29307790cfc462b5b5a605460403f263f955a59350e770531c4aa8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.0.4/clonr_1.0.4_Darwin_arm64.tar.gz"
      sha256 "dfda81c893fbbaf4da0ae4f1e6f6f343b7c496c9306d7aff881193dce8f3ab0d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.0.4/clonr_1.0.4_Linux_x86_64.tar.gz"
      sha256 "516f47dd85bcdb10025b8fee7f4e790161c4ddabba6bdfeec76069a1f0905e30"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.0.4/clonr_1.0.4_Linux_arm64.tar.gz"
      sha256 "dcc6f45403afa632d4d5850af44d398e21600a8422296d802c4ccf250daf976b"
    end
  end

  def install
    bin.install "clonr"
  end
end
