# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clonr < Formula
  desc "A fast and easy to use templating engine."
  homepage ""
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.3.0/clonr_1.3.0_darwin_arm64.tar.gz"
      sha256 "2af04534e8cd08887b0c708d0f9476a22cbf1d5ba5513d77401d4b68ca0b7c55"

      def install
        bin.install "clonr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.3.0/clonr_1.3.0_darwin_amd64.tar.gz"
      sha256 "cde28e4add41887d8c891e8e92923eb865f43db3ebb9f1b7bac96f61bc552d31"

      def install
        bin.install "clonr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.3.0/clonr_1.3.0_linux_armv6.tar.gz"
      sha256 "77c27182a0da3a34b059d5748df2a412e2e4979dae428236155ac2798ef5c50c"

      def install
        bin.install "clonr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.3.0/clonr_1.3.0_linux_arm64.tar.gz"
      sha256 "4ef70913d67459bf15f2489bfbf6ce6af1e072079a65146ea5b3c4023015fc07"

      def install
        bin.install "clonr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oledakotajoe/clonr/releases/download/v1.3.0/clonr_1.3.0_linux_amd64.tar.gz"
      sha256 "ad24755574320b2907511d0a1ede80df67a54bab57dbfd06b69321a9b8c7a52f"

      def install
        bin.install "clonr"
      end
    end
  end
end
